einkaufsliste/einkauf/urls.py
from django.conf.urls.static import static
from django.urls import re_path

from einkaufsliste import settings
from . import views
from .views import ListBookings, ListProducts, UpdateProduct, DeleteProduct
from .views import CreateBookingEntry
from .views import CreateProduct

app_name = 'einkauf'
urlpatterns = [
      re_path(r'^$', ListBookings.as_view(), name='bookingList'),
      re_path(r'^products/$', ListProducts.as_view(), name='productList'),
      re_path(r'^create_product/$', CreateProduct.as_view(), name='createProduct'),
      re_path(r'^update_product/(?P<pk>[\d]+)/$', UpdateProduct.as_view(), name='updateProduct'),
      re_path(r'^delete_product/(?P<pk>[\d]+)/$', DeleteProduct.as_view(), name='deleteProduct'),
      re_path(r'^create_booking/$', CreateBookingEntry.as_view(), name='createBooking'),
      re_path(r'^mark_booking_buyed/(?P<pk>[\d]+)/$', views.markBookingEntryBuyed, name='markBooking'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

einkaufsliste/einkaufsliste/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from einkauf import urls as einkauf

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(einkauf, namespace='einkauf')),

]

einkaufsliste/einkauf/models.py
from django.db import models
from datetime import datetime

from django.urls import reverse


class Categorie(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    categorie = models.ForeignKey(Categorie, default=1, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.today(), blank=True, editable=False)

    def __str__(self):
        if self.description:
            return self.name + '-' + self.description
        else:
            return self.name

    def get_update_view(self):
        return reverse('einkauf:updateProduct', kwargs={
            'pk': self.pk,
        })

    def get_delete_view(self):
        return reverse('einkauf:deleteProduct', kwargs={
            'pk': self.pk,
        })


class Booking(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    purchased = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=datetime.today(), blank=True, editable=False)

    def __str__(self):
        return self.product.name + '-' + str(self.purchased)

einkaufsliste/einkauf/forms.py
from django import forms
from .models import Booking


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['product', ]

einkaufsliste/einkauf/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from .models import Product, Categorie
from .models import Booking
from .forms import BookingForm


@method_decorator(csrf_exempt, name='dispatch')
class CreateProduct(CreateView):
    model = Product
    fields = '__all__'
    template_name = 'form.html'

    def get_success_url(self):
        return reverse('einkauf:createBooking')

    def get_context_data(self, **kwargs):
        context = super(CreateProduct, self).get_context_data(**kwargs)
        context['form_title'] = 'Create Product'
        return context

    def form_valid(self, form):
        return super(CreateProduct, self).form_valid(form)


@method_decorator(csrf_exempt, name='dispatch')
class UpdateProduct(UpdateView):
    model = Product
    fields = '__all__'
    template_name = 'form.html'

    def get_success_url(self):
        return reverse('einkauf:productList')

    def get_context_data(self, **kwargs):
        context = super(UpdateProduct, self).get_context_data(**kwargs)
        context['form_title'] = 'Update Product'
        return context

    def form_valid(self, form):
        return super(UpdateProduct, self).form_valid(form)


@method_decorator(csrf_exempt, name='dispatch')
class DeleteProduct(DeleteView):
    model = Product
    template_name = 'form.html'

    def get_success_url(self):
        return reverse('einkauf:productList')


@method_decorator(csrf_exempt, name='dispatch')
class CreateBookingEntry(CreateView):
    model = Booking
    form_class = BookingForm
    template_name = 'select_item_form.html'

    def get_success_url(self):
        return reverse('einkauf:bookingList')

    def get_context_data(self, **kwargs):
        context = super(CreateBookingEntry, self).get_context_data(**kwargs)
        context['form_title'] = 'Create new entry'
        context['products'] = Product.objects.all().order_by('name')
        context['categorie'] = Categorie.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        form = BookingForm(request.POST)
        if form.is_valid():
            for prod in request.POST.getlist('product'):
                try:
                    booking = Booking()
                    booking.purchased = False
                    booking.product = Product.objects.get(pk=prod)
                    booking.save()
                except ValueError:
                    pass
            return redirect(self.get_success_url())
        else:
            return redirect(self.get_success_url())


class ListBookings(ListView):
    model = Booking
    queryset = Booking.objects.filter(purchased=False)
    template_name = 'list.html'


class ListProducts(ListView):
    model = Product
    queryset = Product.objects.all().order_by('categorie__name', 'name')
    template_name = 'listProducts.html'


@csrf_exempt
def markBookingEntryBuyed(request, pk):
    if request.method == 'POST':
        booking = get_object_or_404(Booking, pk=pk)
        booking.purchased = True
        booking.save()
        return HttpResponse(200)
    else:
        return HttpResponse(404)

einkaufsliste/einkauf/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Einkaufsliste</title>
   <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css">
<style>
    .vertical-text {
	    transform: rotate(90deg);
	    transform-origin: left top 0;
    }
    .btn-bar-left {
        margin-left: 3.8em;
        position: fixed;
    }
    .btn-bar-right {
        margin-left: 1.1em;
        position: fixed;
    }
</style>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
    {% block script %}
    {% endblock %}
</html>

einkaufsliste/einkauf/templates/form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container" style="margin-top: 3em">
        <h2 style="text-align: center">{{ form_title }}</h2>
        <form action="." method="post" style="text-align: center; font-size: 20px">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="list-group">
                <input type="submit" class="btn btn-info btn-lg" value="Eintragen">
                {% if productform %}
                    <a href="{% url 'einkauf:bookingList' %}" class="btn btn-primary btn-lg ">Back</a>
                    <a href="{% url 'einkauf:createProduct' %}" class="btn btn-danger btn-lg ">Create new product</a>
                {% else %}
                    <a href="{% url 'einkauf:createBooking' %}" class="btn btn-primary btn-lg ">Back</a>
                    <a href="{% url 'einkauf:productList' %}" class="btn btn-light" style="float: right">SP</a>
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

{% block script %}
<script>
    $('#id_product').prop('multiple', true);
</script>
{% endblock %}

einkaufsliste/einkauf/templates/list.html
{% include 'base.html' %}
{% block content %}
    <div class="container" onload="autoReload()">
        <nav class="navbar-dark">
            <a href="{% url 'einkauf:createBooking' %}" class="nav-item nav-link btn btn-primary">Create new entry</a>
            <a href="." onclick="reloadPage()" class="nav-item nav-link btn btn-success" style="float: right">Refresh list</a>
        </nav>
        <h2 style="text-align: center">Einkaufsliste</h2>
        <div class="col-sm-12 col-md-12 col-lg-12">
            <table class="table table-bordered table-striped" style="font-size: 16px">
            {% for object in object_list %}
                <tr>
                    <td style="text-align: center" ondblclick="markAsBuyied({{ object.pk }})" id="{{ object.pk }}">
                        {{ object.product.name }}
                        {% if object.product.description %}
                            / {{ object.product.description }}
                        {% endif %}
                        <input type="url" value="{% url 'einkauf:markBooking' object.pk %}"
                               style="display: none" id="mypath_{{ object.pk }}">
                    </td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function () {
       let time = 36000 * 5;
       setTimeout(function () {
           location.reload();
       }, time);
    });

    function markAsBuyied(id) {
        $('#' + id).css('background-color', '#ffaca3');
        var host = $(location).attr('host');
        var path = $('#mypath_' + id).val();
        var url = 'http://' + host + path;
        $.post( url, function( data ) {
            if (data == 200) {
                location.reload();
            }
        });
    }

    function reloadPage() {
        location.reload();
    }
</script>
{% endblock %}

einkaufsliste/einkauf/templates/listProducts.html
{% extends 'base.html' %}
{% block content %}
    <div class="container" onload="autoReload()">
        <nav class="navbar-dark">
            <a href="{% url 'einkauf:bookingList' %}" class="nav-item nav-link btn btn-primary ">Back</a>
            <a href="{% url 'einkauf:createProduct' %}" class="nav-item nav-link btn btn-success" style="float: right">Create product</a>
        </nav>
        <h2 style="text-align: center">Products</h2>
        <div class="col-sm-12 col-md-12 col-lg-12">
            <table class="table table-bordered table-striped" style="font-size: 16px">
            {% for object in object_list %}
                <tr>
                    <td style="text-align: center" >
                        {{ object.name }} {% if object.description %} / {{ object.description }} {% endif %}
                    </td>
                    <td>
                        <a href="{{ object.get_update_view }}" class="btn btn-secondary">Update</a>
                    </td>
                    <td>
                        <a href="{{ object.get_delete_view }}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function () {
       let time = 36000 * 5;
       setTimeout(function () {
           location.reload();
       }, time);
    });

    function markAsBuyied(id) {
        $('#' + id).css('background-color', '#ffaca3');
        var host = $(location).attr('host');
        var path = $('#mypath_' + id).val();
        var url = 'http://' + host + path;
        $.post( url, function( data ) {
            if (data == 200) {
                location.reload();
            }
        });
    }
</script>
{% endblock %}

einkaufsliste/einkauf/templates/select_item_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid" style="margin-top: 3em">
        <h2 style="text-align: center">{{ form_title }}</h2>
        <form action="." method="post" style="text-align: center; font-size: 20px">
            {% csrf_token %}
            <select name="product" required id="id_product" class="custom-select" multiple>
                <option value="-1" class="Diverse">---------</option>
                {% for prod in products %}
                    <option value="{{ prod.pk }}" class="{{ prod.categorie }}">
                        {{ prod.name }}{% if prod.description %} - {{ prod.description }}{% endif %}</option>
                {% endfor %}
            </select>
        <br>
        <label for="id_categorie">Filter: </label>
            <select name="categorie" id="id_categorie" onchange="filter_categories()">
                <option value="none">---------</option>
                {% for cat in categorie %}
                    <option value="{{ cat.name }}">{{ cat.name }}</option>
                {% endfor %}
            </select>
            <div class="list-group">
                <input type="submit" class="btn btn-info btn-lg" value="Eintragen">
                <a href="{% url 'einkauf:bookingList' %}" class="btn btn-primary btn-lg ">Back</a>
                <a href="{% url 'einkauf:createProduct' %}" class="btn btn-danger btn-lg ">Create new product</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block script %}
<script>
    //$('#id_product').prop('multiple', true);

    function filter_categories() {
        var filter_choice = $('#id_categorie').val();
        var prod_list = $('#id_product option');
        prod_list.each(function () {
            if(filter_choice !== $(this).attr('class') && filter_choice !== 'none') {
                $(this).hide();
            } else {
                $(this).show();
            }
        })
    }
</script>
{% endblock %}